{{
  config(
    materialized='view',
    schema='staging'
  )
}}

WITH source AS (
    SELECT
        Product,
        Plant,
        PurchasingGroup,
        CountryOfOrigin,
        RegionOfOrigin,
        ProductionInvtryManagedLoc,
        ProfileCode,
        ProfileValidityStartDate,
        AvailabilityCheckType,
        FiscalYearVariant,
        PeriodType,
        ProfitCenter,
        Commodity,
        GoodsReceiptDuration,
        MaintenanceStatusName,
        IsMarkedForDeletion,
        MRPType,
        MRPResponsible,
        ABCIndicator,
        MinimumLotSizeQuantity,
        MaximumLotSizeQuantity,
        FixedLotSizeQuantity,
        ConsumptionTaxCtrlCode,
        IsCoProduct,
        ProductIsConfigurable,
        StockDeterminationGroup,
        StockInTransferQuantity,
        StockInTransitQuantity,
        HasPostToInspectionStock,
        IsBatchManagementRequired,
        SerialNumberProfile,
        IsNegativeStockAllowed,
        GoodsReceiptBlockedStockQty,
        HasConsignmentCtrl,
        FiscalYearCurrentPeriod,
        FiscalMonthCurrentPeriod,
        ProcurementType,
        IsInternalBatchManaged,
        ProductCFOPCategory,
        ProductIsExciseTaxRelevant,
        BaseUnit,
        ConfigurableProduct,
        GoodsIssueUnit,
        MaterialFreightGroup,
        OriginalBatchReferenceMaterial,
        OriglBatchManagementIsRequired,
        ProductIsCriticalPrt,
        ProductLogisticsHandlingGroup
    FROM {{ source('sap', 'A_ProductPlantType') }}
)

SELECT
    CAST(Product AS STRING) AS product_id,
    CAST(Plant AS STRING) AS plant_code,
    CAST(PurchasingGroup AS STRING) AS purchasing_group,
    CAST(CountryOfOrigin AS STRING) AS country_of_origin,
    CAST(RegionOfOrigin AS STRING) AS region_of_origin,
    CAST(ProductionInvtryManagedLoc AS STRING) AS production_inventory_location,
    CAST(ProfileCode AS STRING) AS profile_code,
    PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S', SPLIT(ProfileValidityStartDate, '/Date(')[OFFSET(1)]) AS profile_validity_start_date,
    CAST(AvailabilityCheckType AS STRING) AS availability_check_type,
    CAST(FiscalYearVariant AS STRING) AS fiscal_year_variant,
    CAST(PeriodType AS STRING) AS period_type,
    CAST(ProfitCenter AS STRING) AS profit_center,
    CAST(Commodity AS STRING) AS commodity_code,
    CAST(GoodsReceiptDuration AS NUMERIC) AS goods_receipt_duration,
    CAST(MaintenanceStatusName AS STRING) AS maintenance_status,
    CAST(IsMarkedForDeletion AS BOOLEAN) AS is_marked_for_deletion,
    CAST(MRPType AS STRING) AS mrp_type,
    CAST(MRPResponsible AS STRING) AS mrp_responsible,
    CAST(ABCIndicator AS STRING) AS abc_indicator,
    CAST(MinimumLotSizeQuantity AS NUMERIC) AS minimum_lot_size,
    CAST(MaximumLotSizeQuantity AS NUMERIC) AS maximum_lot_size,
    CAST(FixedLotSizeQuantity AS NUMERIC) AS fixed_lot_size,
    CAST(ConsumptionTaxCtrlCode AS STRING) AS consumption_tax_code,
    CAST(IsCoProduct AS BOOLEAN) AS is_co_product,
    CAST(ProductIsConfigurable AS STRING) AS is_configurable,
    CAST(StockDeterminationGroup AS STRING) AS stock_determination_group,
    CAST(StockInTransferQuantity AS NUMERIC) AS stock_in_transfer,
    CAST(StockInTransitQuantity AS NUMERIC) AS stock_in_transit,
    CAST(HasPostToInspectionStock AS BOOLEAN) AS has_inspection_stock,
    CAST(IsBatchManagementRequired AS BOOLEAN) AS batch_management_required,
    CAST(SerialNumberProfile AS STRING) AS serial_number_profile,
    CAST(IsNegativeStockAllowed AS BOOLEAN) AS negative_stock_allowed,
    CAST(GoodsReceiptBlockedStockQty AS NUMERIC) AS blocked_stock_quantity,
    CAST(HasConsignmentCtrl AS STRING) AS has_consignment_control,
    CAST(FiscalYearCurrentPeriod AS STRING) AS fiscal_year_period,
    CAST(FiscalMonthCurrentPeriod AS STRING) AS fiscal_month_period,
    CAST(ProcurementType AS STRING) AS procurement_type,
    CAST(IsInternalBatchManaged AS BOOLEAN) AS internal_batch_managed,
    CAST(ProductCFOPCategory AS STRING) AS cfop_category,
    CAST(ProductIsExciseTaxRelevant AS BOOLEAN) AS excise_tax_relevant,
    CAST(BaseUnit AS STRING) AS base_unit,
    CAST(ConfigurableProduct AS STRING) AS configurable_product_id,
    CAST(GoodsIssueUnit AS STRING) AS goods_issue_unit,
    CAST(MaterialFreightGroup AS STRING) AS freight_group,
    CAST(OriginalBatchReferenceMaterial AS STRING) AS original_batch_material,
    CAST(OriglBatchManagementIsRequired AS STRING) AS original_batch_required,
    CAST(ProductIsCriticalPrt AS BOOLEAN) AS is_critical_part,
    CAST(ProductLogisticsHandlingGroup AS STRING) AS logistics_handling_group
FROM source
