{{
  config(
    materialized='view',
    schema='staging'
  )
}}

SELECT
  PurchaseOrder AS purchase_order_id,
  CompanyCode AS company_code,
  PurchaseOrderType AS purchase_order_type,
  PurchasingDocumentDeletionCode AS deletion_indicator,
  PurchasingProcessingStatus AS processing_status,
  CreatedByUser AS created_by_user,
  CreationDate AS creation_date,
  LastChangeDateTime AS last_change_datetime,
  Supplier AS supplier_id,
  PurchaseOrderSubtype AS purchase_order_subtype,
  Language AS language_code,
  PaymentTerms AS payment_terms,
  CashDiscount1Days AS cash_discount_1_days,
  CashDiscount2Days AS cash_discount_2_days,
  NetPaymentDays AS net_payment_days,
  CashDiscount1Percent AS cash_discount_1_percent,
  CashDiscount2Percent AS cash_discount_2_percent,
  PurchasingOrganization AS purchasing_organization,
  PurchasingDocumentOrigin AS document_origin,
  PurchasingGroup AS purchasing_group,
  PurchaseOrderDate AS order_date,
  DocumentCurrency AS currency_code,
  ExchangeRate AS exchange_rate,
  ExchangeRateIsFixed AS exchange_rate_fixed,
  ValidityStartDate AS validity_start_date,
  ValidityEndDate AS validity_end_date,
  SupplierQuotationExternalID AS supplier_quotation_id,
  PurchasingCollectiveNumber AS collective_number,
  SupplierRespSalesPersonName AS supplier_sales_person,
  SupplierPhoneNumber AS supplier_phone,
  SupplyingSupplier AS supplying_supplier_id,
  SupplyingPlant AS supplying_plant,
  IncotermsClassification AS incoterms,
  CorrespncExternalReference AS external_reference,
  CorrespncInternalReference AS internal_reference,
  InvoicingParty AS invoicing_party,
  ReleaseIsNotCompleted AS release_not_completed,
  PurchasingCompletenessStatus AS completeness_status,
  IncotermsVersion AS incoterms_version,
  IncotermsLocation1 AS incoterms_location_1,
  IncotermsLocation2 AS incoterms_location_2,
  ManualSupplierAddressID AS manual_address_id,
  IsEndOfPurposeBlocked AS purpose_blocked,
  AddressCityName AS supplier_city,
  AddressFaxNumber AS supplier_fax,
  AddressHouseNumber AS supplier_house_number,
  AddressName AS supplier_name,
  AddressPostalCode AS supplier_postal_code,
  AddressStreetName AS supplier_street,
  AddressPhoneNumber AS supplier_phone_number,
  AddressRegion AS supplier_region,
  AddressCountry AS supplier_country,
  AddressCorrespondenceLanguage AS correspondence_language,
  PurgAggrgdProdCmplncSuplrSts AS compliance_status,
  PurgAggrgdProdMarketabilitySts AS marketability_status,
  PurgAggrgdSftyDataSheetStatus AS safety_sheet_status,
  PurgProdCmplncTotDngrsGoodsSts AS dangerous_goods_status,
  YY1_HeaderRetention_PDH AS header_retention,
  YY1_RetentionType_PDH AS retention_type,
  YY1_MaxRetention_PDH AS max_retention,
  YY1_HeaderRetention_PDHF AS header_retention_flag,
  YY1_MaxRetention_PDHF AS max_retention_flag,
  YY1_RetentionType_PDHF AS retention_type_flag,
  YY1_RetentionType_PDHT AS retention_type_text
FROM {{ source('sap', 'A_PurchaseOrderType') }}
